Import('env')

sources = Split('''
	commands.c
	common.c
	data.c
	error.c
	file_system.c
	geometry.c
	model_shape.c
	model_shape_cmds.c
	script.c
	stream.c
	stream_file.c
	stream_mem.c
	text.c
	vars.c
	wrapper.c
	gl/framebuffer.c
	gl/model.c
	gl/shader.c
	gl/texture.c
''')

scripts = Split('''
	scripts/common.lua
	scripts/class.lua
	scripts/wrapper.lua
	scripts/model.lua
''')

if env['PLATFORM'] == 'darwin':
	sources.append('gl/system_sdl.c')

if env['PLATFORM'] == 'raspi':
	sources.append('gl/system_raspi.c')


sources.append(env.Resources('scripts', scripts))

env.Library('../lib/albase', sources)
