Import('env')

sources = Split('''
	host.c
	file_system.c
	graphics_text.c
	text.c
	widget.c
	graphics.c
''')

shaders = Split('''
	shaders/widget.vert
	shaders/widget.frag
	shaders/model.vert
	shaders/model.frag
	shaders/text.vert
	shaders/text.frag
	shaders/cursor.vert
	shaders/cursor.frag
''')

scripts = Split('''
	scripts/file_widget.lua
	scripts/widget.lua
	scripts/draggable.lua
	scripts/toolbar.lua
	scripts/slider_widget.lua
	scripts/colour_widget.lua
	scripts/model_widget.lua
	scripts/text_box.lua
	scripts/panning_widget.lua
	scripts/model_view_model.lua
''')

images = Split('''
	images/font.png
	images/cursor.png
''')

sources.append(env.Resources('shaders', shaders))
sources.append(env.Resources('scripts', scripts))
sources.append(env.Resources('images', images))

env.Library('../lib/alice', sources)
